### ISSUE TITLE
StopSearcher query is slow 

### ISSUE THREAD

**Issue by rockwood** [gaslight/bus-detective#1]
@mguterl, would you mind taking a look at

https://github.com/gaslight/bus-detective/blob/master/app/models/stop_searcher.rb

To get a stops routes, we have to query through `stops -> stop_times -> trips -> routes` and it's pretty slow. Is there an index I can add to speed things up?

**Comment by mguterl** [comment]
@rockwood - I'll try to take a look at this over the weekend. If indexing doesn't work, it may be possible to denormalize some of the information.

**Comment by mguterl** [comment]
@rockwood can you give me an example of where this is particularly slow? Is it slow on your machine or just heroku? Are there certain stops that perform worse than others?

**Comment by rockwood** [comment]
Take a look at http://busdetective.com/api/stops?query=main.

![image](https://cloud.githubusercontent.com/assets/659052/7445280/32862fb6-f17a-11e4-861b-e964c00b8f96.png)

It can often take > 5 seconds to respond, but I'm not entirely sure it's the query that's slow.

**Comment by rockwood** [comment]
Seems to be working :+1: 

![image](https://cloud.githubusercontent.com/assets/659052/7447898/019c0e2a-f1d9-11e4-94f1-c4251cc8f9cb.png)
