### ISSUE TITLE
When searching for stops, users should be able to see the full list

### ISSUE THREAD

**Issue by Nate-Wessel** [gaslight/bus-detective#13]
My usual stop is "Main St & 13th St" (outbound)
Here's the problem: a search for "main" returns 20 results with the word "Main" in the name, but my stop is not among them. So, issue 1 is that there are not enough results. I have also had this problem using the location search, where I've run out of search results before I find my stop.

**Comment by geofflane** [comment]
I'm going to split these into 2 issues.

**Comment by geofflane** [comment]
This could be by returning them all or paginating

**Comment by rockwood** [comment]
@geofflane With the API now supporting pagination, can we close this?

**Comment by Nate-Wessel** [comment]
Not yet. There's no interface in the app yet to allow pagination or the display of further results. That's the important bit.

**Comment by geofflane** [comment]
@Nate-Wessel The UI is in there. If you search for Main, for example, you'll see next/previous arrows at the top of the screen.

**Comment by Nate-Wessel** [comment]
Only in the name search, not in the location search.

**Comment by geofflane** [comment]
We might need pagination in the distance search too?

**Comment by Nate-Wessel** [comment]
I mean, it's probably not as necessary as for the name search, but I had trouble finding my stop using the distance search.

**Comment by rockwood** [comment]
Just pushed a fix for this. You should now see pagination on the nearby stops page.
