### ISSUE TITLE
android splash image distortion

### ISSUE THREAD

**Issue by Nate-Wessel** [gaslight/bus-detective#18]
Home screen image is squashed when using the android app. It's either not wide enough or too tall. It looks fine when viewed with just a browser.

**Comment by ktornwall** [comment]
@Nate-Wessel What model phone are you using? OS version?

**Comment by Nate-Wessel** [comment]
I used two different devices and got the same problem.
The first is a Motorola phone, model #XT907 running 4.4.2. The second is an Asus Tablet, model #K010 running 4.4.2.
