### ISSUE TITLE
Stop location icon image seems to be broken

### ISSUE THREAD

**Issue by Nate-Wessel** [gaslight/bus-detective#19]
On the little map on the arrival predictions pages, the icon on the map showing the location of the stop seems to be broken. If I try to view the icon/image by itself, by right clicking on it, I see the following:

'The image “http://busdetective.com/assets/images/marker-icon.png” cannot be displayed because it contains errors.'

Using firefox on my laptop.

**Comment by Nate-Wessel** [comment]
I love the new OSM map by the way!

**Comment by geofflane** [comment]
@Nate-Wessel Yeah, we saw this. I keep giving @cdmwebs a hard time trying to get him to fix it. :)

**Comment by geofflane** [comment]
Fixed this.
