### ISSUE TITLE
Question about DepartureFetcher#stop_times

### ISSUE THREAD

**Issue by mguterl** [gaslight/bus-detective#6]
DepartureFetcher#stop_times depends on a time (now) and stop id in order to return recent and upcoming departures for a stop.

Recent departures are within the last 10 minutes.
Upcoming departures are within the next hour.

Also, stop times are only returned if they have a trip with a service day of today (for example thursday).

Given that the current time is Friday at 11:59pm
Then the start time is 11:49pm
And the end time is 12:59am
And the service day is Friday

I think that this means stop times for Saturday won't show up, even though they are within the next hour, because they are being scoped by service day.

I used the time 11:59pm, but I believe this happens starting at 11, with any stop times after midnight.

Does it make sense to be able to query across different service days? I came across this when doing some research on changing the /api/departures endpoint to take start_time and end_time as parameters.

**Comment by rockwood** [comment]
Yes, that is correct. It seems like we should change `Service.for_time(time)` to something like `Service.in_range(start_time, end_time)` that could return services across multiple days.

**Comment by mguterl** [comment]
If stop times are being filtered by departure_time, what is the reason for scoping by service day? Is it a performance thing?

**Comment by rockwood** [comment]
The stop_times.departure_time column is a Time, not a DateTime so that only tells you at what time of day a bus will come. The services table defines what trips are active for a given day of the week. We query both to get stop_times that are active today and are within the time range

**Comment by rockwood** [comment]
The data is modeled just as it comes from the the [GTFS files](https://developers.google.com/transit/gtfs/reference). I'd be down with exploring alternatives to make it easier to query.

**Comment by geofflane** [comment]
+1 Just ran into this tonight.

**Comment by geofflane** [comment]
I think this is more than just a range because we need to join services to trips to ensure that there is service on the given "next day"

**Comment by mguterl** [comment]
I actually think my initial report is off. The issue happens at 8:00pm not midnight like I thought.

**Comment by geofflane** [comment]
It's "Midnight" UTC. 8PM EST.

**Comment by geofflane** [comment]
When the query crosses a day boundary it's just wrong:

```
IN (SELECT "services"."id" FROM "services" WHERE (tuesday)) AND "stop_times"."stop_id" = 1256 AND (departure_time > '2015-05-12 23:40:03.510844' AND departure_time < '2015-05-13 01:40:03.510844')
```

Greater than 23 and less than 1 will never be true.

**Comment by rockwood** [comment]
Well there's your problem right there

**Comment by rockwood** [comment]
the StopTime GTFS data we import represents after-midnight arrival times as > 24 hours (see https://developers.google.com/transit/gtfs/reference#stop_times_fields). I build Metro::TimeParser to convert those into valid time strings, but know that may be useful for this issue.

**Comment by Nate-Wessel** [comment]
I'm not sure if this will be helpful, but the stop time values are in 'interval' format. To get the correct timestamp of any stop time, simply add the interval to the date of the service day, which should return a timestamp(or something that could be cast as a timestamp).

**Comment by geofflane** [comment]
@Nate-Wessel I think you're right. We had been converting the intervals to times which is incorrect. It wouldn't work properly around daylight savings time changes and some other things either.

**Comment by geofflane** [comment]
We've got the interval based method of calculating stop times in now, so this should be fixed for real.
